### ISSUE TITLE
Godot Engine 4.0 module fails to compile

### ISSUE THREAD

**Issue by fire** [ashtonmeuser/godot-wasm#20] opened 2023-05-02 03:31 UTC
Can you confirm?

**Comment by ashtonmeuser** [comment] 2023-05-02 04:15
@fire I'll take a look. Out of curiosity, are you able to use it as a Godot 3 module? What about as an addon with Godot 3 or 4?

**Comment by fire** [comment] 2023-05-02 12:57
I haven’t seriously worked in godot 3 for 3 years :/

**Comment by ashtonmeuser** [comment] 2023-05-02 13:56
Thanks for the input, all. Should be fixed.

> The define should probably be swapped to being defined in the case of extension builds. As with modules the define wont be present when register_types.h is used by the code gen.

Done using `GDNATIVE` C++ define in _SCsub_.

> Also these methods should be removed completely.

Done.

> Last thing there are a lot of #ifdef GDNATIVE's in the code. Just seems a bit odd. Is it being used as a define for GDEXtension here?

Kinda. The define will still exist but never be present in the Godot 4 branch. This is used when Godot 3 modules, GDExtension, and Godot 4 modules all use the same API and GDNative is the only one that differs e.g. method registration. Could remove this vestige from the Godot 4 branch but keeping it in allows the two main branches to remain more similar and thus easier to resolve conflicts.

> After that is fixed there seems to be a lot of issues with the stream-peer class.

Done. Few more odd defines to resolve the difference between StreamPeer and StreamPeerExtension.

**Comment by fire** [comment] 2023-05-02 14:14
I can check in in 12 hours, but if someone can confirm it works you can close the issue.

**Comment by Trey2k** [comment] 2023-05-02 14:52
It now compiles, however it fails at the linking stage.
```
[ 91%] progress_finish(["progress_finish"], [])
[ 94%] Linking Static Library servers/libservers.linuxbsd.editor.x86_64.a ...
Ranlib Library servers/libservers.linuxbsd.editor.x86_64.a ...
[ 94%] Linking Static Library core/libcore.linuxbsd.editor.x86_64.a ...
Ranlib Library core/libcore.linuxbsd.editor.x86_64.a ...
[ 94%] scons: *** [bin/godot.linuxbsd.editor.x86_64] Implicit dependency `modules/wasm/wasmer/lib/libwasmer.linuxbsd.editor.x86_64.a' not found, needed by target `bin/godot.linuxbsd.editor.x86_64'.
scons: building terminated because of errors.
[Time elapsed: 00:04:33.480]
```
 I think this is caused by: https://github.com/ashtonmeuser/godot-wasm/blob/121540bf2ef55993ff1b934c2b1855b9d7ebdcf9/SCsub#L17
 
as it should be looking for `libwasmer.a` not `libwasmer.linuxbsd.editor.x86_64.a`

**Comment by ashtonmeuser** [comment] 2023-05-02 15:03
Glad to hear! Gonna close this but feel free to reopen if this continues to be an issue.

**Closed by ashtonmeuser** 2023-05-02 15:03 UTC

**Comment by fire** [comment] 2023-05-02 15:14
I personally use modules because I prefer to ship a binary and a pck. So I'm biased towards modules. As far as I know GDExtension allows creating extensions of classes while gdnative is like a script on an existing class. Not sure that helps.

**Comment by fire** [comment] 2023-05-02 15:45
I will pending compiling the module.

**Comment by fire** [comment] 2023-05-03 04:14
@ashtonmeuser I was able to get the build to run locally, but had some problems fetching the wasm. There's no way to fetch the was and bundling all cicd platforms is a bit ugly

https://github.com/V-Sekai/godot/tree/wasm

**Comment by ashtonmeuser** [comment] 2023-05-03 04:40
@fire Awesome that's a good start! Loving all the feedback and bug reports! Does #22 sufficiently capture what you're saying?
